---
- name: 'deploy basic firewall security'
  ansible.builtin.lineinfile:
    path: '/etc/sysconfig/iptables'
    insertbefore: '-A INPUT -p tcp -m tcp -m multiport --dports 5666,45100 -j ACCEPT'
    line: "-A INPUT -s {{ item }} -j ACCEPT"
  with_items:
    - "{{ hostvars['localhost']['lst_ips'] }}" 

- name: 'restart all servers'
  ansible.builtin.reboot: