---
- name: 'stop and disable nginx'
  ansible.builtin.service:
    name: 'iptables'
    state: started
    enabled: yes

- name: 'reboot all instances'
  ansible.builtin.reboot:

- name: 'wait for masteer to become available'
  ansible.builtin.wait_for:
    port: 45100
    host: "{{ hostvars['localhost']['lst_ips'][0] }}"
    search_regex: OpenSSH
    delay: 10
  connection: local