---
- name: 'start and enablee iptables'
  ansible.builtin.service:
    name: 'iptables'
    state: started
    enabled: yes

- name: 'reboot all instances'
  ansible.builtin.reboot:

- name: 'wait for all nodes to become available'
  ansible.builtin.wait_for:
    port: 45100
    host: "{{ hostvars['localhost']['lst_ips'] }}"
    search_regex: OpenSSH
    delay: 10
  connection: local