---
- name: 'install cri-o'
  ansible.builtin.yum:
    lock_timeout: 90
    name: "{{ item }}"
    state: latest
  with_items:
    - 'cri-tools'
    - 'cri-o'

- name: 'start cri-o service'
  ansible.builtin.service:
    name: 'crio'
    state: started
    enabled: yes

- name: 'install calico cni'
  ansible.builtin.shell:
    cmd: "crictl pull --creds {{ hostvars['localhost']['dokuser'] }}:{{ hostvars['localhost']['dokpass'] }} docker.io/calico/{{ item }}"
  with_items:
    - 'kube-controllers:v3.27.2'
    - 'cni:v3.27.2'
    - 'typha:v3.27.2'
    - 'node-driver-registrar:v3.27.2'