---
- name: 'install cri-o'
  ansible.builtin.yum:
    lock_timeout: 90
    name: 'cri-o'
    state: latest

- name: 'start cri-o service'
  ansible.builtin.service:
    name: 'crio'
    state: started
    enabled: yes

- name: 'install calico cni'
  ansible.builtin.shell:
    cmd: "crictl pull --creds fierce.brake@gmail.com:dckr_pat_LQNgjuv7Qlq8_vtovVOGHSGYUps docker.io/calico/{{ item }}"
  with_items:
    - 'kube-controllers:v3.27.2'
    - 'cni:v3.27.2'
    - 'typha:v3.27.2'
    - 'node-driver-registrar:v3.27.2'