---
- name: 'coopy repositories over'
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: './roles/os/files/cri-o.repo', dest: '/etc/yum.repos.d/cri-o.repo'}
    - {src: './roles/os/files/kubernetes.repo', dest: '/etc/yum.repos.d/kubernetes.repo'}

- name: 'install dependency packages'
  ansible.builtin.yum:
    lock_timeout: 90
    name: 
      - 'socat'
      - 'iproute-tc'
      - 'conntrack-tools'
    state: latest

- name: 'k8s bash completion'
  ansible.builtin.lineinfile:
    path: '/root/.bashrc'
    line: 'source /usr/share/bash-completion/bash_completion'
    state: present

- name: 'load overlay and br_netfilter mods'
  ansible.builtin.command: "modprobe {{ item }}"
  with_items:
    - 'overlay'
    - 'br_netfilter'

- name: 'permanently enable overlay and br_netfilter'
  ansible.builtin.lineinfile:
    path: '/etc/modules-load.d/k8s.conf'
    line: "{{ item }}"
    create: yes
    state: present
  with_items:
    - 'overlay'
    - 'br_netfilter'

- name: 'permanently enable ip_forward'
  ansible.builtin.lineinfile:
    path: '/etc/sysctl.conf'
    line: "{{ item }}"
    state: present
  with_items:
    - 'net.ipv4.ip_forward = 1'
    - 'net.bridge.bridge-nf-call-iptables = 1'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: 'enable ip_fwd'
  ansible.builtin.command: "sysctl -w {{ item }}"
  with_items:
    - 'net.ipv4.ip_forward=1'
    - 'net.bridge.bridge-nf-call-iptables=1'
    - 'net.bridge.bridge-nf-call-ip6tables=1'

- name: 'Apply sysctl params without reboot'
  ansible.builtin.command: 'sysctl --system'
  
- name: 'set hosts files'
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: "{{ ips[item] }} {{ servers[item] }}"
    state: present
  with_items: "{{ range(0, servers | length) }}"