---
- name: 'Collect instance IP'
  amazon.aws.ec2_instance_info:
    region: 'us-east-1'
    filters:
      "tag:Name": "ec2-tcc-{{ custenvi }}-{{ custname }}"
      instance-state-name: [ "running"]
  register: ec2

- ansible.builtin.debug:
    msg: "ec2-tcc-{{ custenvi }}-{{ custname }}"

- ansible.builtin.debug:
    var: ec2.instances[0].private_ip_address

- name: 'export variables'
  ansible.builtin.set_fact:
    pri_ip: "{{ ec2.instances[0].private_ip_address }}"