---
- name: 'Collect instance IP'
  amazon.aws.ec2_instance_info:
    region: 'us-east-1'
    filters:
      instance-state-name: ["running"]
      availability-zone: us-east-1
      "tag:Name": "ec2-tcc-dev-demos-*"
  register: servers

- name: 'create list variable'
  ansible.builtin.set_fact:
    lst_ips: []

- name: 'saving ips in a list'
  ansible.builtin.set_fact:
    lst_ips: "{{ lst_ips + [servers.instances[item].private_ip_address] }}"
  loop: "{{ range(0, servers.instances|length) }}"

- name: 'store servers sufix'
  ansible.builtin.set_fact:
    lst_servers: "{{ name_sf }}"
    k8s_version: '1.28.3'
    ctd_version: '1.7.8'
    rnc_version: '1.1.10'
    cni_version: '1.3.0'
    cri_version: '1.28.0'
    cidr: '192.168.0.0/16'

- name: 'Refresh inventory'
  meta: refresh_inventory