---
- name: 'Collect instance IP'
  amazon.aws.ec2_instance_info:
    region: 'us-east-1'
    filters:
      # "tag:Name": "ec2-tcc-{{ custenvi }}-{{ custname }}"
      instance-state-name: ["running"]
  register: servers

# - ansible.builtin.debug:
#     msg: "ec2-tcc-{{ custenvi }}-{{ custname }}"

# - ansible.builtin.debug:
#     var: ec2.instances[0].private_ip_address

# - name: 'export variables'
#   ansible.builtin.set_fact:
#     pri_ip: "{{ ec2.instances[0].private_ip_address }}"

- ansible.builtin.debug:
    var: servers

- name: 'create list variable'
  ansible.builtin.set_fact:
    lst_ips: []

- name: 'saving ips in a list'
  ansible.builtin.set_fact:
    lst_ips: "{{ lst_ips + [servers.instances[item].private_ip_address] }}"
  loop: "{{ range(0, 3) }}"

- ansible.builtin.debug:
    var: hostvars['localhost']['lst_ips']

- name: 'store servers sufix'
  ansible.builtin.set_fact:
    lst_servers: "{{ name_sf }}"
    k8s_version: '1.28.3'
    ctd_version: '1.7.8'
    rnc_version: '1.1.10'
    cni_version: '1.3.0'
    cri_version: '1.28.0'
    cidr: '192.168.0.0/16'

- name: 'Refresh inventory'
  meta: refresh_inventory