---
- name: 'Collect instance IP'
  amazon.aws.ec2_instance_info:
    region: 'us-east-1'
    filters:
      instance-state-name: ["running"]
  register: servers

- name: 'create list variable'
  ansible.builtin.set_fact:
    lst_ips: []

- name: 'saving ips in a list'
  ansible.builtin.set_fact:
    lst_ips: "{{ lst_ips + [servers.instances[item].private_ip_address] }}"
  loop: "{{ range(0, servers.instances|length) }}"

- name: 'store servers sufix'
  ansible.builtin.set_fact:
    lst_servers: "{{ name_sf }}"
    k8s_version: '1.29.2'
    ctd_version: '1.7.11'
    rnc_version: '1.1.11'
    cni_version: '1.2.0'
    cri_version: '1.29.0'
    cidr: '192.168.0.0/16'
    dokuser: "{{ dokuser }}"
    dokpass: "{{ dokpass }}"

- name: 'Refresh inventory'
  meta: refresh_inventory