---
- name: 'join nodes'
  ansible.builtin.shell: 
    cmd: "sudo {{ joinnode }} --ignore-preflight-errors=all"
    chdir: '/usr/local/bin'
  async: 90
  poll: 0
  register: nodejoinoutput

- ansible.builtin.debug:
    var: nodejoinoutput