---
- name: 'create manifests directory'
  ansible.builtin.file:
    path: '/etc/kubernetes/manifests'
    state: directory
    mode: '0775'  

- name: 'join nodes'
  ansible.builtin.shell: 
    cmd: "{{ joinnode }}"
  async: 90
  poll: 0 
  register: nodejoin

- ansible.builtin.debug:
    var: nodejoin