---
- name: 'create manifests directory'
  ansible.builtin.file:
    path: '/etc/kubernetes/manifests'
    state: directory
    mode: '0775'  

- name: 'join nodes'
  ansible.builtin.shell: 
    cmd: "{{ joinnode }}"
  async: 90
  poll: 0 
  register: nodejoin

- ansible.builtin.debug:
    var: nodejoin

- name: 'nodes firewall security'
  ansible.builtin.lineinfile:
    path: '/etc/sysconfig/iptables'
    insertafter: '-A INPUT -i lo -j ACCEPT'
    line: "{{ item }}"
  with_items:
    - '-A INPUT -p tcp --dport 10251 -m comment --comment "node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 10255 -m comment --comment "node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 30080 -m comment --comment "nodeport traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 8080 -m comment --comment "app traffic" -j ACCEPT'