---
- name: 'cluster bootstrap'
  ansible.builtin.shell: 
    cmd: "/usr/bin/kubeadm init --pod-network-cidr {{ hostvars['localhost']['cidr'] }} --apiserver-advertise-address {{ hostvars['localhost']['lst_ips'][0] }} --kubernetes-version {{ hostvars['localhost']['k8s_version'] }} --node-name {{ hostvars['localhost']['lst_servers'][0] }}"
    chdir: '/root'
    creates: cluster_initialized.txt

- name: 'configure root account as cluster admin'
  ansible.builtin.file:
    path: '/root/.kube'
    state: directory

- name: 'copy user config file'
  ansible.builtin.copy:
    remote_src: 'yes'
    src: '/etc/kubernetes/admin.conf'
    dest: '/root/.kube/config'
    owner: 'root'
    group: 'root'
    
- name: 'calico yaml copy'
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
  with_items:
    - {src: './roles/master/files/calico.yaml', dest: '/root/calico.yaml'}
    - {src: './roles/master/files/java-hw.yml', dest: '/root/java-hw.yml'}

- name: 'calico pod network deployment'
  ansible.builtin.shell: 
    cmd: "sudo /usr/bin/kubectl create -f /root/calico.yaml"
    chdir: '/usr/bin'
  async: 90
  poll: 0 

- name: 'master firewall security'
  ansible.builtin.lineinfile:
    path: '/etc/sysconfig/iptables'
    insertafter: '-A INPUT -i lo -j ACCEPT'
    line: "{{ item }}"
  with_items:
    - '-A INPUT -p tcp --dport 6443 -m comment --comment "master node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 2379:2380 -m comment --comment "master node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 10250 -m comment --comment "master node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 10251 -m comment --comment "master node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 10252 -m comment --comment "master node traffic" -j ACCEPT'
    - '-A INPUT -p tcp --dport 10255 -m comment --comment "master node traffic" -j ACCEPT'

- name: 'print-join-command'
  ansible.builtin.shell: 
    cmd: '/usr/bin/kubeadm token create --print-join-command'
  register: 'joincommand'

- name: 'store variables'
  set_fact:
    joinmaster: "{{ joincommand.stdout }}"