---
- name: 'stop and disable nginx'
  ansible.builtin.service:
    name: 'nginx'
    state: stopped
    enabled: no

- name: 'get instances'
  hosts: localhost
  become: 'True'
  become_user: 'root'
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
   - aws

- name: 'install and copnfigure packages on all servers'
  hosts: "{{ hostvars['localhost']['lst_ips'] }}" 
  port: '45100'
  become: 'True'
  become_user: 'root'
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
   - os

- name: 'cluster bootstrap'
  hosts: "{{ hostvars['localhost']['lst_ips'][0] }}"
  port: '45100'
  become: 'True'
  become_user: 'root'
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - master

- name: 'join nodes to cluster'
  hosts: "{{ hostvars['localhost']['lst_ips'] | difference(hostvars['localhost']['lst_ips'][0]) }}"
  port: '45100'
  become: 'True'
  become_user: 'root'
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - nodes

- name: 'deploy app'
  hosts: "{{ hostvars['localhost']['lst_ips'][0] }}"
  port: '45100'
  become: 'True'
  become_user: 'root'
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
   - restart