---
- name: 'install cri-o'
  ansible.builtin.yum:
    lock_timeout: 90
    name: "{{ item }}"
    state: latest
  with_items:
    - 'kubelet'
    - 'kubeadm'
    - 'kubectl'

- name: 'start cri-o service'
  ansible.builtin.service:
    name: 'kubelet'
    state: started
    enabled: yes